# Generated by Django 5.1.7 on 2025-04-06 07:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('spot_number', models.IntegerField(unique=True)),
                ('is_occupied', models.BooleanField()),
                ('lot_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parkinglot')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleEntry',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('license_plate', models.CharField(max_length=10)),
                ('qr_code', models.CharField(max_length=255)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField()),
                ('spot_uuid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.parkingspot')),
            ],
        ),
    ]
